version: 2
updates:

  # .github/workflows/*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # go.mod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # EOF
