sudo: required
language: ruby
services:
- docker
env:
  global:
  - DOCKER_USERNAME=docwhat
  - secure: "aZ/joaAXK05pMt6uSFuY4LH0h051BZQpdOD4NBMU0JvKM0Z4BpMr1D4JLnnQECvapVQlJicyukNdXdS0OSr12w0H28fsFZaTiOnNps4PkxSyDlSK8ByBByPVwGySn3iT4soIQMAicXwKr+I2zTbc1hd88K2tXLX5O0Pg+G/r3Br4mYXg7eZMWYwWFauQ+/zgRKINab8tvupiK4L6c8lH7QtCEEyNbe0UdjyUh+kQKnQxazr5IO+Rht/H9eIVbrEN6FpRdICdNW5f643/6vxpZehI1n/OGXO5iVdImyx7SbtXaUW54S8/hQ1unYMJUZADdTwMVRcNNNsTir5Xyee5IG9gsp41j3ldRuSjKf7wDL1sIw7Z4OnRjFycWulsyhySsX4hcD85IWqDY6of4CULNksEOp1ww4sq2OsdRDCjrysKQ6d7mXFoJ2BD1V82252Z4DcKhuOb0gBzyCuEVrnh2DNz9F4aWjHUiF6BYUdrDIlGMxzwmu6RR/g+Ridui9kZq2V7GEsX9HMWOA1LP+9UUFM8zwLADlWDgMLBa4/u5c0Sc/8OYOE5+kDNSo6bGqa/+0+Gx5TdBwWv43X2fx5okuhWovTSk/pAYueNJkRhggd+mj6dBfBQPGQdupvIhaIt5lyj2gM3T7mufZ+3FeMcCtttks0lKyY1r43r8o6a+Ok="
install: true
script: script/build
deploy:
  provider: script
  script: script/push "docwhat/street_cleaning:latest"
  on:
    branch: master
notifications:
  email:
    on_failure: never
    on_success: never
  pushover:
    api_key:
      secure: "M4bS9rKziwk0pZl9vivXCVMekIIIdxx1b3A5qaO3WHlGaTHBHu2FcXefNKgvuhKvjBiAMWewjHrttiNs1DfSp9EY1OQs6293GnePePhWtTMLkJFsS05lsodPlVBa88r5ksUGZr1XoDNtmu0DALKMBmfxu3ibpJZDzI/oc1hKjca58z1LaRjD4zI6sDRE8ePQsor9oVoP2bxBxmfIM19LY/2OW91V9moJf2tPoo/RtMEeD190thMeVIM7YpZ3Pon42Xip6eNWVQFdCyWThMttxQKNPcr1+NkqzCKYEJsfZVEvWJKVfGtnsmOKAua/9aPXXxmI6wfReZQnMOV5/Vvs+qqzWgk9cHZjuqoispNGOCWR3YbZyuI1myo+nx4RRCEo8LH0KmerpcbZ4vEXe9AP6ewRbc+k/XVZsMutA6UoV0c9Q0iIgLkR/vwaT+xEVpruTNw61IJs0qQZJJip9vcswxvxKYMDV1Zt+aaePQeTUWJ5vDH0QH7yq23joN3dDjDOo6A50AU7aJDRxVWWp3q2wc5KZLtoOKKQFFheS/dtv+zqmJar4dWpU+QHYULXDr9mXLeQGMZ8HUy790ZoWqYPQ9NmxZlXjGYHdjBeyTGLDfDMaJ7HeW2cmCYOHLtSo9dEOuLDCIguedYtxwLxfSVynOdALJyNHNWhlk4DipTa4nI="
    on_failure: always
    on_success: change
    users:
      secure: "c2IGWJmEBFZFUzSdpbDWFreTkOo9tgIKgSGr1+PIBKug1AffdFlqhVLwkxTJxQntQ7wcRdI2o2x1NlW6wPpsoIf8nCyGvyPMdcZ/5icFuIiQz5AHEDn0f8/5GO2owKPoeH/Pt1H86k0sD7YOIqi50RCxwh27baHztJc0kSErCL7ayVIf7YATQqTkXhSPpB5HZb65BOEMVcj/v7lNB6rNGoUelLFpAJesPbc6dkb41CyEDX36OqhD+4DfQyCPBqDeOsPydjpAOSmrPhLUcB9o45yh8vx/Oy8wno6MwzjUcfxjJazzaysdx8lo1gi+fdNVRMZBZxMghzjmDIAdp2INKT8OW9fSOpMcFujvgLu6HVgmMK2XD9yGZhDVqgC0Stgy/jNsvs0Ftp6dwLIWWedFzRS0oKVdJjG7CVowQBWdsfW4v1YI3+MgrXDFzwieIID5eH3tI38M4EMuJ139nub9Dq61o/1Btuc3I23GS2ra1bZMb36uYsrnYdkIefqTxI+lwZHnO+a9ewAe5D1Z/UVcULCkKlf58tPscuK7FxFq7JNz8D4sv7HJqZRtA/c0/N6SeDCITxaLx4Mot9t6NkCLB/nmhhu4GYSYeRAq5gRjpydsZ5WiMNr7wJTV2CpaWc+cWrSQj4y64WJXgmnRT2hGNXhc0k2nEPCZ8vZdx0yPH98="
  webhooks:
    - "https://www.travisbuddy.com/"
