---
"name": CI

"on":
  pull_request: {}
  push:
    branches:
      - main

"jobs":
  build:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # For better sonar analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          repository: "${{github.repository}}/street-cleaning-calendar"
          add_git_labels: true
          tag_with_sha: true
          tags: latest
