---
"name": CI

"on":
  pull_request: {}
  push:
    branches:
      - main

"jobs":
  build:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          repository: "${{github.repository}}/street-cleaning-calendar"
          add_git_labels: true
          tag_with_sha: true
          tags: latest
